[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''if first_pass and not (_c.set == 'Edition') and badges then'''
position = "before"
payload = '''
if FlowerPot.rev_lookup_records[_c.key] then
    local card_progress = G.PROFILES[G.SETTINGS.profile].joker_usage[_c.key] or {}

    FlowerPot.rev_lookup_records[_c.key]:add_tooltips(info_queue, card_progress, card)
end
'''
match_indent = true